### ISSUE TITLE
Chrome Update

### ISSUE THREAD

**Issue by BrunoMartinsCorrea** [flathub/com.rtosta.zapzap#6]
First of a all, thanks and congrats to build this app!

I have installed the package yesterday (2022-01-31) and was working fine, but after a reboot this happened...

![image](https://user-images.githubusercontent.com/11370034/151973082-e5b31038-235e-4200-9eef-abe9744f7542.png)

**Comment by rafatosta** [comment]
Correction already made, just wait.
Thanks for the feedback. =D
![image](https://user-images.githubusercontent.com/18619894/151982899-d6e32465-ae57-4212-98b1-19dcecacc1e0.png)
