### ISSUE TITLE
Window Bar Decoration is not consistent with the rest of the system in Ubuntu 23.10

### ISSUE THREAD

**Issue by volanin** [flathub/com.rtosta.zapzap#67]
Hello Rafael,

Ubuntu 23.10 (and the upcoming 24.04 LTS) uses Gnome and Wayland. When running Zapzap, the Window Bar Decoration does not match the rest of the system. I searched online and found that to make Qt Applications work correctly in Wayland, I should export QT_QPA_PLATFORM=xcd before launching the application, but this caused a missing plugin problem.

![Screenshot from 2024-01-07 12-44-37](https://github.com/flathub/com.rtosta.zapzap/assets/7845195/1dfa02ef-5485-4c8e-9edf-3763f55c09d3)

Please, see the screenshots attached.
Zapzap is **flatpak**, Textpad and Terminal are **native** (deb), and Skype and Firefox are **snaps**.

![Screenshot from 2024-01-07 12-41-43](https://github.com/flathub/com.rtosta.zapzap/assets/7845195/34369584-20d4-44d2-a796-65643c4465f8)

By the way, do you have any intention of creating a Zapzap snap someday?
Thanks a lot!

**Comment by rafatosta** [comment]
Use Flatseal to disable Wayland and make it run on X11.

About snap, yes I'm interested, I just don't have the time.

**Comment by volanin** [comment]
It works!
But now the fonts are blurry, really blurry, to the point I actually prefer the inconsistent decoration!
I am using gnome's fractional scaling 125% which might cause that, although in "wayland mode" the zapzap fonts are perfect.
