### ISSUE TITLE
Cedilla is not working when using US-International

### ISSUE THREAD

**Issue by volanin** [flathub/com.rtosta.zapzap#74]
I know this might be just a silly configuration, but I really can't get cedilla to work with my US-International keyboard.
When I press **Accent + C**, I get the character **ć** instead of **ç**

I am using flatpak in Ubuntu 23.10 (Gnome) and Xubuntu 22.04 (Xfce4)... both have the same problem.
In all other applications (both native and flatpak ones) it works correctly.
The problem is just in ZapZap.

I already tried setting these environment variables using flatseal:

_GTK_IM_MODULE=cedilla_
_QT_IM_MODULE=cedilla_

But it didn't work.
Could you help me fix this, please?

**Comment by AxeldeWater** [comment]
Are you sure that you are in the right repository? You might want to ask it [here](https://github.com/zapzap-linux/zapzap) instead, unless you are sure that this has something to do with Flathub/flatpak.

**Comment by volanin** [comment]
You're right, thanks for the correct link.
