### ISSUE TITLE
org.kde.Platform 6.5 end-of-life

### ISSUE THREAD

**Issue by nlogozzo** [flathub/com.rtosta.zapzap#84]
```
Info: runtime org.kde.Platform branch 6.5 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Platform and SDK
Info: applications using this runtime:
   com.rtosta.zapzap
```

**Comment by rafatosta** [comment]
> ```
> Info: runtime org.kde.Platform branch 6.5 is end-of-life, with reason:
>    We strongly recommend moving to the latest stable version of the Platform and SDK
> Info: applications using this runtime:
>    com.rtosta.zapzap
> ```

Unfortunately, I had to downgrade until I was able to resolve a problem I was having with KDE6 and the most current version, 6.7, of the runtime.

Thank you very much for your understanding.
